[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "leetcode"
version = "0.0.1"

[tool.setuptools.packages.find]
where = ["."]

[tool.black]
line-length = 80